repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  slf4j_api: org.slf4j:slf4j-api:jar:1.7.10
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.7.10
